version: '3'

services:

  mdns:
    image: brewblox/brewblox-mdns:${BREWBLOX_RELEASE:-stable}
    network_mode: host
    restart: unless-stopped

  eventbus:
    image: rabbitmq:alpine
    restart: unless-stopped

  influx:
    image: influxdb
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_LOGGING_LEVEL=warn
      - INFLUXDB_DATA_WAL_FSYNC_DELAY=1s
      - INFLUXDB_DATA_INDEX_VERSION=tsi1

  datastore:
    image: treehouses/couchdb
    restart: unless-stopped
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./couchdb/:/opt/couchdb/data/

  spark-one:
    image: brewblox/brewblox-devcon-spark:${BREWBLOX_RELEASE:-stable}
    privileged: true
    depends_on:
      - eventbus
      - datastore
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark-one"
    command: >
      --name=spark-one

  history:
    image: brewblox/brewblox-history:${BREWBLOX_RELEASE:-stable}
    depends_on:
      - influx
      - eventbus
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  ui:
    image: brewblox/brewblox-ui:${BREWBLOX_RELEASE:-stable}
    restart: unless-stopped
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    command: -c /config/traefik.toml --docker --docker.domain=brewblox.local
